import "./globals.css";

import { Inter } from "next/font/google";

import Header from "@/lib/components/Layout/Header";
import Footer from "@/lib/components/Layout/Footer";
import { ThemeProvider } from "@/lib/theme/ThemeProvider";
import AuthProvider from "@/lib/config/AuthProvider";
import MobileFooter from "@/lib/components/Layout/MobileFooter";
import api from "@/lib/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crex",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const allInternationalSeries = await api.series.getInternationalSeries();
  const allLeagueSeries = await api.series.getLeagueSeries();
  const allWomenSeries = await api.series.getWomenSeries();

  // Combine the series data from all three calls
  const allSeries = allInternationalSeries?.concat(
    allLeagueSeries,
    allWomenSeries
  );

  // Now allSeries contains the combined series data
  console.log("allSeries", allSeries);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Header allSeries={allSeries} />
            {children}
            <Footer />
            <MobileFooter />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
