import "./globals.css";

import { Inter } from "next/font/google";

import Header from "@/lib/components/Layout/Header";
import Footer from "@/lib/components/Layout/Footer";
import { ThemeProvider } from "@/lib/theme/ThemeProvider";
import AuthProvider from "@/lib/config/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Crex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
